version: '3.1'
networks:
  millipede_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

services:
  db:
    build:
      context: ../
      dockerfile: docker/mysql/Dockerfile
    container_name: millipede-mysql
    networks:
          millipede_net:
            ipv4_address: 172.19.0.2
    environment:
      MYSQL_ROOT_PASSWORD: millipede123
      MYSQL_DATABASE: millipede
      MYSQL_USER: millipede
      MYSQL_PASSWORD: millipede123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  php-fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    container_name: millipede-php-fpm
    depends_on:
      - db
    networks:
      millipede_net:
        ipv4_address: 172.19.0.3
    working_dir: /var/www/millipede
    privileged: true
    volumes:
##      - ./php-fpm/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
##      - ./php-fpm/ssmtp/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini
      - ./php-fpm/configuration.ini:/usr/local/etc/php/conf.d/configuration.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../app/symfony:/var/www/millipede
  web:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    container_name: millipede-webserver
    depends_on:
      - php-fpm
    networks:
      millipede_net:
        ipv4_address: 172.19.0.4
    working_dir: /var/www/millipede/public
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf/symfony.conf:/etc/nginx/conf.d/symfony.conf
      - ../app/symfony:/var/www/millipede
