version: '3.1'
networks:
  phalcon_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

services:
#  db:
#    build:
#      context: ../
#      dockerfile: docker/mysql/Dockerfile
#    container_name: phalcon-mysql
#    networks:
#          phalcon_net:
#            ipv4_address: 172.19.0.2
#    environment:
#      MYSQL_ROOT_PASSWORD: phalcon123
#      MYSQL_DATABASE: phalcon
#      MYSQL_USER: phalcon
#      MYSQL_PASSWORD: phalcon

  php-fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    container_name: phalcon-php-fpm
    networks:
      phalcon_net:
        ipv4_address: 172.19.0.3
    working_dir: /var/www/millipede
    volumes:
      - ../:/var/www/millipede
      - /www/millipede/docker/
#    links:
#      - db

  web:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    container_name: phalcon-webserver
    networks:
      phalcon_net:
        ipv4_address: 172.19.0.4
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf/millipede.conf:/etc/nginx/conf.d/millipede.conf
      - ../:/var/www/millipede
      - /www/millipede/docker/
    links:
      - php-fpm

  phalcon:
    build:
      context: ../
      dockerfile: docker/phalcon/Dockerfile
    container_name: phalcon-framework
    networks:
          phalcon_net:
            ipv4_address: 172.19.0.5
    working_dir: /var/www/millipede
    volumes:
      - ../:/var/www/millipede
      - /www/millipede/docker/
    links:
      - php-fpm
      - web