controllers:
    resource: '../src/Controller/'
    type: annotation

index:
    path: /
    controller: App\Controller\DefaultController::index

random:
    path: /random
    controller: App\Controller\RandomController::random

millipede:
    path: /millipede
    controller: App\Controller\MillipedeController::millipede