<?php
/**
 * Created by PhpStorm.
 * User: mtrybula
 * Date: 17.03.19
 * Time: 23:08
 */

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class CurrentDevelopersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

}